const data = [
  {
    id: 1,
    location: "İstanbul, Türkiye",
    shortDescription: "Ev sahibi Ahmet Bey.",
    availability: "27 May - 1 Haz",
    price: 12500,
    rate: 4.8,
    special: true,
    photo: "https://picsum.photos/200/300?random=1",
  },
  {
    id: 2,
    location: "Antalya, Türkiye",
    shortDescription: "Plaja 50 metre mesafede.",
    availability: "28 May - 2 Haz",
    price: 10500,
    rate: 4.6,
    special: false,
    photo: "https://picsum.photos/200/300?random=2",
  },
  {
    id: 3,
    location: "İzmir, Türkiye",
    shortDescription: "Şehir manzaralı.",
    availability: "29 May - 3 Haz",
    price: 9500,
    rate: 4.7,
    special: true,
    photo: "https://picsum.photos/200/300?random=3",
  },
  {
    id: 4,
    location: "Bodrum, Türkiye",
    shortDescription: "Deniz manzaralı.",
    availability: "30 May - 4 Haz",
    price: 11500,
    rate: 4.9,
    special: false,
    photo: "https://picsum.photos/200/300?random=4",
  },
  {
    id: 5,
    location: "Çeşme, Türkiye",
    shortDescription: "Ev sahibi Hasan Bey.",
    availability: "31 May - 5 Haz",
    price: 9800,
    rate: 4.5,
    special: true,
    photo: "https://picsum.photos/200/300?random=5",
  },
  {
    id: 6,
    location: "Ankara, Türkiye",
    shortDescription: "Ev sahibi Zeynep Hanım.",
    availability: "1 Haz - 6 Haz",
    price: 8800,
    rate: 4.4,
    special: false,
    photo: "https://picsum.photos/200/300?random=6",
  },
  {
    id: 7,
    location: "Adana, Türkiye",
    shortDescription: "Bahçe manzaralı.",
    availability: "2 Haz - 7 Haz",
    price: 9100,
    rate: 4.3,
    special: true,
    photo: "https://picsum.photos/200/300?random=7",
  },
  {
    id: 8,
    location: "Trabzon, Türkiye",
    shortDescription: "Plaja 100 metre mesafede.",
    availability: "3 Haz - 8 Haz",
    price: 10200,
    rate: 4.5,
    special: false,
    photo: "https://picsum.photos/200/300?random=8",
  },
  {
    id: 9,
    location: "Gaziantep, Türkiye",
    shortDescription: "Ev sahibi Ali Bey.",
    availability: "4 Haz - 9 Haz",
    price: 9300,
    rate: 4.2,
    special: true,
    photo: "https://picsum.photos/200/300?random=9",
  },
  {
    id: 10,
    location: "Bursa, Türkiye",
    shortDescription: "Doğa manzaralı.",
    availability: "5 Haz - 10 Haz",
    price: 10400,
    rate: 4.6,
    special: false,
    photo: "https://picsum.photos/200/300?random=10",
  },
  {
    id: 11,
    location: "Kayseri, Türkiye",
    shortDescription: "Şehir merkezine yakın.",
    availability: "6 Haz - 11 Haz",
    price: 8900,
    rate: 4.3,
    special: true,
    photo: "https://picsum.photos/200/300?random=11",
  },
  {
    id: 12,
    location: "Mersin, Türkiye",
    shortDescription: "Ev sahibi Mehmet Bey.",
    availability: "7 Haz - 12 Haz",
    price: 9700,
    rate: 4.4,
    special: false,
    photo: "https://picsum.photos/200/300?random=12",
  },
  {
    id: 13,
    location: "Eskişehir, Türkiye",
    shortDescription: "Parka 50 metre mesafede.",
    availability: "8 Haz - 13 Haz",
    price: 8600,
    rate: 4.2,
    special: true,
    photo: "https://picsum.photos/200/300?random=13",
  },
  {
    id: 14,
    location: "Konya, Türkiye",
    shortDescription: "Ev sahibi Fatma Hanım.",
    availability: "9 Haz - 14 Haz",
    price: 9200,
    rate: 4.5,
    special: false,
    photo: "https://picsum.photos/200/300?random=14",
  },
  {
    id: 15,
    location: "Van, Türkiye",
    shortDescription: "Göl manzaralı.",
    availability: "10 Haz - 15 Haz",
    price: 9800,
    rate: 4.3,
    special: true,
    photo: "https://picsum.photos/200/300?random=15",
  },
  {
    id: 16,
    location: "Malatya, Türkiye",
    shortDescription: "Ev sahibi Hasan Bey.",
    availability: "11 Haz - 16 Haz",
    price: 9100,
    rate: 4.4,
    special: false,
    photo: "https://picsum.photos/200/300?random=16",
  },
  {
    id: 17,
    location: "Erzurum, Türkiye",
    shortDescription: "Dağ manzaralı.",
    availability: "12 Haz - 17 Haz",
    price: 8700,
    rate: 4.6,
    special: true,
    photo: "https://picsum.photos/200/300?random=17",
  },
  {
    id: 18,
    location: "Diyarbakır, Türkiye",
    shortDescription: "Ev sahibi Zeynep Hanım.",
    availability: "13 Haz - 18 Haz",
    price: 9400,
    rate: 4.5,
    special: false,
    photo: "https://picsum.photos/200/300?random=18",
  },
  {
    id: 19,
    location: "Samsun, Türkiye",
    shortDescription: "Plaja 200 metre mesafede.",
    availability: "14 Haz - 19 Haz",
    price: 9500,
    rate: 4.7,
    special: true,
    photo: "https://picsum.photos/200/300?random=19",
  },
  {
    id: 20,
    location: "Kocaeli, Türkiye",
    shortDescription: "Ev sahibi Ayşe Hanım.",
    availability: "15 Haz - 20 Haz",
    price: 9300,
    rate: 4.4,
    special: false,
    photo: "https://picsum.photos/200/300?random=20",
  },
  {
    id: 21,
    location: "Sakarya, Türkiye",
    shortDescription: "Orman manzaralı.",
    availability: "16 Haz - 21 Haz",
    price: 9400,
    rate: 4.5,
    special: true,
    photo: "https://picsum.photos/200/300?random=21",
  },
  {
    id: 22,
    location: "Tekirdağ, Türkiye",
    shortDescription: "Ev sahibi Ahmet Bey.",
    availability: "17 Haz - 22 Haz",
    price: 9200,
    rate: 4.2,
    special: false,
    photo: "https://picsum.photos/200/300?random=22",
  },
  {
    id: 23,
    location: "Hatay, Türkiye",
    shortDescription: "Denize 150 metre uzaklıkta.",
    availability: "18 Haz - 23 Haz",
    price: 8800,
    rate: 4.3,
    special: true,
    photo: "https://picsum.photos/200/300?random=23",
  },
  {
    id: 24,
    location: "Kütahya, Türkiye",
    shortDescription: "Ev sahibi Ayşe Hanım.",
    availability: "19 Haz - 24 Haz",
    price: 9300,
    rate: 4.4,
    special: false,
    photo: "https://picsum.photos/200/300?random=24",
  },
  {
    id: 25,
    location: "Afyon, Türkiye",
    shortDescription: "Kaplıca manzaralı.",
    availability: "20 Haz - 25 Haz",
    price: 9500,
    rate: 4.6,
    special: true,
    photo: "https://picsum.photos/200/300?random=25",
  },
];
export default data;
